# Generated by Django 4.0.6 on 2022-11-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_photo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_is_html',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
